

---  
   - name: install and configure DB  
     hosts: localhost
     become: yes

     vars:
      oracle_db_port_value: 1521
     

     tasks:
      - name: install oracle_db
        yum: yum -y install oracle-database-ee-18c 

          